= Collect of various scripts for working with EDA-tools (ASIC, FPGA, etc)
Dmitry Murzinov <kakstattakim@gmail.com>
v1.0, 6.7.2016
:doctype: article
:lang: en
:stem:
:grid: all
:align: center
:imagesdir: example???
:homepage: http://idoka.ru

== Intro

I hope that helps not only me


== Script collection

=== UCF2XDC converter

The `ucf-to-xdc.sh` script for Xilinx EDA-tools: that convert ISE-style to Vivado-style constraints (sdc -> xdc)

Detailed description:
include::ucf-to-xdc.adoc[leveloffset=+2]


=== Vivado usage runtime statistic

The `vivado-stat.sh` script for Xilinx Vivado-tool: that prints CPU and Memory usage of all instances of Vivado tools

Detailed description:
include::vivado-stat.adoc[leveloffset=+2]


=== Fake NIC create 

The `fake-nic.sh` script for creating the (additional) HostID if your laptop don't have any wired Ethernet Adapter or many other cases :)

Detailed description:
include::fake-nic.adoc[leveloffset=+2]

TIP: By the way Latest version of FLEXLM and SCL supports multiple HostID at same time, i.e. all eth* (not only eth0)


== References

* scratch.adoc[Notes]

////
* http://www.redhat.com/[RedHat]
* http://www.centos.org/[CentOS]
* http://www.xilinx.com/[Xilinx]
* http://www.altera.com/[Altera]
////

