puts ""
puts "------------------------------------------------------------------------------------"
puts "| Tool Version : Vivado v.2020.1 (lin64) Build 2902540 Wed May 27 19:54:35 MDT 2020"
puts "| Date         : Sat Aug 15 14:36:25 2020"
puts "| Host         : doka running 64-bit CentOS Linux release 7.8.2003 (Core)"
puts "| Command      : report_utilization -hierarchical -hierarchical_depth 2"
puts "| Design       : xdma_top"
puts "| Device       : xcku115flvb2104-2"
puts "| Design State : Routed"
puts "------------------------------------------------------------------------------------"
puts ""
puts "################################################################################"
puts "# STEP#1: define constraints"
puts "################################################################################"
puts "#set_property CONFIG_VOLTAGE                      1.8 "
puts "#set_property CFGBVS                              GND "
puts "#set_property BITSTREAM.GENERAL.COMPRESS         TRUE "
puts "#set_property CONFIG_MODE                     {SPIx8} "
puts "#set_property BITSTREAM.CONFIG.PERSIST         SPIx8  "
puts "#set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN div-1 "
puts "#set_property BITSTREAM.CONFIG.SPI_FALL_EDGE      YES "
puts "#set_property BITSTREAM.config.SPI_opcode        0x6B "
puts "#set_property BITSTREAM.CONFIG.UNUSEDPIN     Pulldown "
puts "#set_property HD.TANDEM_IP_PBLOCK    Stage1_Config_IO "
puts "#set_property HD.TANDEM_IP_PBLOCK    Stage1_Main      "
puts ""
puts ""
puts "WARNING: (Synth 8-7071) port 'pipe_tx0_rcvr_det' of module 'xdma_0_core_top' is unconnected for instance 'inst' "
puts "INFO: \[Synth 8-6155\] done synthesizing module 'user_reg' (9#1) "
puts "INFO: \[Synth 8-6155\] done synthesizing module 'xdma_app' (10#1)"
puts "INFO: \[Synth 8-6155\] done synthesizing module 'xdma_top' (11#1)"
puts "INFO: \[Synth 8-3886\] merging instance 'dma_pcie_rc/pfch_rc_parityerr_reg\[0\]' (FDRE) to 'dma_pcie_rc/pfch_rc_parityerr_reg\[7\]'"
puts ""

puts ""
puts "CRITICAL WARNING: (Vivado 12-180) No cells matched 'get_cells -hierarchical -filter { NAME =~ *rxlpmen_i_reg\[*\]}'. "
puts ""
puts "Starting Placer Task"
puts "INFO: (Place 30-611) Multithreading enabled for place_design using a maximum of 6 CPUs"
puts ""
puts "Phase 1.2 IO Placement/ Clock Placement/ Build Placer Device"
puts "WARNING: (Place 30-781) Some instances may violate an exclude pblock as they constitute a macro with another instance that belongs to the exclude pblock."
puts "Exclude pblock: xdma_0_i_inst_pcie3_ip_i_inst_Stage1_cfgiob"
puts ""

puts "Phase 10 Post Router Timing | Checksum: 2a8535c47"
puts ""
puts "INFO: (Common 17-349) Got license for feature 'Implementation' and/or device 'xcku115'"
puts ""
puts "WNS: 1.284 ns (setup)"
puts "WNS: 0.030 ns (hold)"
puts ""
puts "INFO: (DRC 23-27) Running DRC with 6 threads"
puts "WARNING: (DRC RTSTAT-10) No routable loads: 6 net(s) have no routable loads. The problem bus(es) and/or net(s) are xdma_0_i/inst/pcie3_ip_i/inst/cfg_ltssm_state_reg0\[5:0\]."
puts "INFO: (Vivado 12-3199) DRC finished with 0 Errors, 1 Warnings"
puts "INFO: (Vivado 12-3200) Please refer to the DRC report (report_drc) for more information."
puts "INFO: (Designutils 20-2272) Running write_bitstream with 6 threads."
puts ""
puts "Loading data files..."
puts "Loading site data..."
puts "Loading route data..."
puts "Processing options..."
puts "INFO: (Designutils 12-2358) Enabled Tandem boot bitstream."
puts ""
puts ""
puts "ERROR: just for example"
puts ""
